### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by avanier**
Suggests the addition of a Dockerfile.

### CODE REVIEW

**Comment by avanier** [comment]
bump

**Comment by avanier** [comment]
@denderello I get the feeling this repo isn't watched by anyone? Is there someone at GiantSwarm I can poke?

**Comment by denderello** [comment]
Not sure about this, but you can try to reach out to @xh3b4sd, @teemow or @JosephSalisbury 😄

**Comment by JosephSalisbury** [comment]
Hey! Thanks for bearing with us. Merging <3

**Pull request merged**
